apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: weatherforecast-dev-digitalproduct
  description: weatherforecast system
  annotations:
    argocd/app-name: weatherforecast-dev
    github.com/project-slug: Cegeka-Nitro/weatherforecast-prerepo
  tags:
    - dotnet
    - dev
  links:
    - url: https://weatherforecastapi.weatherforecast-dev.dev.nitro.cegeka.com//swagger/index.html
      title: Swagger
spec:
  owner: Nitro
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weatherforecast-dev-weatherforecastapi-component
  description: weatherforecast component
  annotations:
    github.com/project-slug: Cegeka-Nitro/weatherforecast-prerepo
    argocd/app-name: weatherforecast-dev
    backstage.io/kubernetes-label-selector: app=weatherforecastapi
  tags:
    - dotnet
    - dev
spec:
  type: website
  lifecycle: experimental
  owner: Nitro
  system: weatherforecast-dev-digitalproduct
  providesApis:
    - weatherforecastapi-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weatherforecast-dev-weatherforecastapi-api
  description: weatherforecast API
  annotations:
    github.com/project-slug: Cegeka-Nitro/weatherforecast-prerepo
    argocd/app-name: weatherforecast-dev
    backstage.io/kubernetes-label-selector: app=weatherforecastapi
  tags:
    - dotnet
    - dev
  links:
    - url: https://weatherforecastapi.weatherforecast-dev.dev.nitro.cegeka.com//swagger/index.html
      title: Swagger
spec:
  type: openapi
  lifecycle: experimental
  owner: Nitro
  system: weatherforecast-dev-digitalproduct
  definition: |
    {
      "openapi": "3.0.1",
      "info": {
        "title": "Weatherforecast.Demo",
        "version": "1.0"
      },
      "paths": {
        "/WeatherForecast": {
          "get": {
            "tags": [
              "WeatherForecast"
            ],
            "operationId": "GetWeatherForecast",
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/WeatherForecast"
                      }
                    }
                  },
                  "application/json": {
                    "schema": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/WeatherForecast"
                      }
                    }
                  },
                  "text/json": {
                    "schema": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/WeatherForecast"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {
          "WeatherForecast": {
            "type": "object",
            "properties": {
              "date": {
                "type": "string",
                "format": "date-time"
              },
              "temperatureC": {
                "type": "integer",
                "format": "int32"
              },
              "temperatureF": {
                "type": "integer",
                "format": "int32",
                "readOnly": true
              },
              "summary": {
                "type": "string",
                "nullable": true
              }
            },
            "additionalProperties": false
          }
        }
      }
    }
